name: souqe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.0
  firebase_auth: ^4.17.3
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^19.1.0
  cloud_firestore: ^4.17.5
  firebase_analytics: ^10.8.0
  awesome_dialog: ^3.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/apple.png
    - assets/images/logo.png
    - assets/images/bagPhoto.png
    - assets/images/back.png
    - assets/images/banana.png
    - assets/images/beef.png
    - assets/images/chicken.png
    - assets/images/banner1.png
    - assets/images/pulses.png
    - assets/images/rice.png
    - assets/images/pepper.png
    - assets/images/logo2.png
    - assets/images/ginger.png
    - assets/images/oil.png
    - assets/images/egg.png
    - assets/images/mastercard.png
    - assets/images/order_success.png
    - assets/images/order_failed.png
    - assets/images/delivery_bike.png
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
